[package]
name = "perft"
version = "0.1.0"
edition = "2024"

[dependencies]
aether-types = { workspace = true }
board = { workspace = true }
movegen = { workspace = true }

[dev-dependencies]
board = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "perft"
harness = false
